ROLES = [
"Top",
"Jungle",
#"River", 
"Mid",
"Adc",
"Support"
]


BOOTS = [
"Berserker's Greaves",
"Mobility Boots",
"Boots of Swiftness",
"Ionian Boots of Lucidity",
"Mercury's Treads",
"Plated Steelcaps",
"Sorcerer's Shoes",
]

MYTHICS = [
"Crown of the Shattered Queen",
"Divine Sunderer",
"Duskblade of Draktharr",
"Eclipse",
"Evenshroud",
"Everfrost",
"Frostfire Gauntlet",
"Galeforce",
"Goredrinker",
"Hextech Rocketbelt",
"Immortal Shieldbow",
"Imperial Mandate",
"Kraken Slayer",
"Liandry's Anguish",
"Locket of the Iron Solari",
"Luden's Tempest",
"Moonstone Renewer",
"Night Harvester",
"Prowler's Claw",
"Riftmaker",
"Shurelya's Battlesong",
"Stridebreaker",
"Sunfire Aegis",
"Trinity Force",
"Turbo Chemtank"]

ITEMS = [
"Abyssal Mask",
"Anathema's Chains",
"Archangel's Staff",
"Ardent Censer",
"Axiom Arc",
"Banshee's Veil",
"Black Cleaver",
"Black Mist Scythe",
"Blade of the Ruined King",
"Bloodthirster",
"Bulwark of the Mountain",
"Chempunk Chainsword",
"Chemtech Putrifier",
"Cosmic Drive",
"Dead Man's Plate",
"Death's Dance",
"Demonic Embrace",
"Edge of Night",
"Essence Reaver",
"Fimbulwinter",
"Force of Nature",
"Frozen Heart",
"Gargoyle Stoneplate",
"Guardian Angel",
"Guinsoo's Rageblade",
"Horizon Focus",
"Hullbreaker",
"Infinity Edge",
"Knight's Vow",
"Lich Bane",
"Lord Dominik's Regards",
"Manamune",
"Maw of Malmortius",
#"Mejai's Soulstealer",
"Mercurial Scimitar",
"Mikael's Blessing",
"Morellonomicon",
"Mortal Reminder",
"Muramana",
"Nashor's Tooth",
"Navori Quickblades",
"Pauldrons of Whiterock",
"Phantom Dancer",
"Rabadon's Deathcap",
"Randuin's Omen",
"Rapid Firecannon",
"Ravenous Hydra",
"Redemption",
"Runaan's Hurricane",
"Rylai's Crystal Scepter",
"Seraph's Embrace",
"Serpent's Fang",
"Serylda's Grudge",
"Shadowflame",
"Shard of True Ice",
"Silvermere Dawn",
"Spirit Visage",
"Staff of Flowing",
"Sterak's Gage",
"Stormrazor",
"The Collector",
"Thornmail",
"Titanic Hydra",
"Umbral Glaive",
"Vigilant Wardstone",
"Void Staff",
"Warmog's Armor",
"Winter's Approach",
"Wit's End",
"Youmuu's Ghostblade",
"Zeke's Convergence",
"Zhonya's Hourglass",
]

RUNES = {
  "Precision" : [
    ["Press the attack", "Lethal tempo", "Fleet footwork", "Conqueror"],
    ["Overheal", "Triumph", "Presence of mind"],
    ["Legend: Alacrity", "Legend: Tenacity", "Legend: Bloodline"],
    ["Coup de grace", "Cut down", "Last stand"]
  ],
  "Domination" : [
    ["Electrocute", "Predator", "Dark harvest", "Hail of blades"],
    ["Cheap shot", "Taste of blood", "Sudden impact"],
    ["Zombie ward", "Ghost poro", "Eyeball collection"],
    ["Ravenous hunter", "Ingenious hunter", "Relentless hunter", "Ultimate hunter"]
  ],
  "Sorcery" : [
    ["Summon aery", "Arcane comet", "Phase rush"],
    ["Nullifying orb", "Manaflow band", "Nimbus cloak"],
    ["Trancendence", "Celerity", "Absolute focus"],
    ["Scorch", "Waterwalking", "Gathering storm"]
  ],
  "Resolve" : [
    ["Grasp of the undying", "Aftershock", "Guardian"],
    ["Demolish", "Font of life", "Shield bash"],
    ["Conditioning", "Second wind", "Bone plating"],
    ["Overgrowth", "Revitalize", "Unflinching"]
  ],
  "Inspiration" : [
    ["Glacial augment", "Unsealed spellbook", "First strike"],
    ["Hextech flashtraption", "Magical footwear", "Perfect timing"],
    ["Future's market", "Minion dematerializer", "Biscuit delivery"],
    ["Cosmic insight", "Approach velocity", "Time warp tonic"]
  ],
  }

QUOTES = [
  "Let's make this fun.",
  "Teach them to fear us",
  "Cut them from this world.",
  "Justice, will be served.",
  "Who want's the piece of the champ.",
  "House, always wins.",
  "Hut, two, three, four.",
  "Come on, does this look dangerous to you.",
  "You only have to click once, fool.",
  "Don't die yet, that was a warning shot.",
  "Cost of your life is one arrow.",
  "Oke.",
  "First destroy, then improve.",
  "Your will, my hands.",
  "It must be done.",
  "Soon, there will be nothing.",
  "Why, because I can.",
  "With pleasure.",
  "Mess with the bull and you get the horns.",
  "Time to feast",
  "Beaten by a little girl.",
  "You hou hou and a bottle of, RUM!",
  "This will be a slaughter.",
  "I am the blade in the darkness.",
  # found on reddit
  "The darker the night, the brighter the stars.",
  "Me, mad? Ahaha...quite likely",
  "Poor lost souls...",
  "Death?...No, nothing that simple.",
  "When lost in utter darkness, there is nothing left but forward",
  "Bwowowow",
  "Beware a man with nothing to lose.",
  "Pain is my gift to you.",
  "You need not follow, but you must witness",
  "Our seasons are reversed: my spring, your fall.",
  "You can't milk those!",
  "Seriously, again? Just drop it.",
  "You will lose",
  "Time flies like an arrow, fruit flies like banana.",
  "I'd rather make mistakes than make nothing at all",
  "The cycle of life and death continues. We will live, they will die.",
  "I was hiding! Hehehaha! Grr!",
  "Trespassers will be shot, then looted, then... chewed on for a while.",
  "Shootings easy! Aiming's hard...",
  "Plenty more where that came from! Seriously, I carry a lot of ammo.",
  "There is life, there is death, and then there is me",
  "Screaming won't do you any good, but it's music to my ears",
  "What delightful agony we shall inflict.",
  "FEEDING TIME!",
  "Say hello to the winds of-AGHAGAHG... oh, I don't know what came over me.",
  "Nom nom nom nom nom nom nom!",
  "The sunshine tastes so good today.",
  "The key to immortality? Not dying.",
  "Let's be friends forever.",
  "See? It's just a scarecrow.",
  "It's hunting us. It knows what we're afraid of.",
  "To shake, or not to shake.",
  "Cheater's just a fancy word for winner."
]

SHARDS = [
  ["Adaptive Force", "Attack speed", "Ability haste"],
  ["Adaptive Force", "Armor", "Magic resistance"],
  ["Health", "Armor", "Magic resistance"]
]

ABILITIES = ['Q', 'W', 'E']